# Generated by Django 4.1.7 on 2023-07-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_category_description_category_is_featured_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
