# Generated by Django 4.1.7 on 2023-07-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_alter_category_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
